backend:
  name: github
  repo: mkllr888/mkdocs-material-boilerplate-1
  branch: master

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "doc"
    label: "Doc"
    folder: "docs_sample"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
  - name: "extensions"
    label: "Extensions"
    folder: "docs_sample/extensions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
  - name: "asdf"
    label: "asdf"
    folder: "docs_sample/asdf"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}